# Generated by Django 3.2.8 on 2021-10-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Įveskite užsakymo numerį numerį', max_length=200, verbose_name='Numeris')),
                ('ordered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('order placed', 'Order placed'), ('in progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='order placed', help_text='Status', max_length=12)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Įveskite produkto numerį', max_length=200, verbose_name='Numeris')),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('ordered', 'Ordered')], default='available', help_text='Status', max_length=12)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='default.png', upload_to='product_pictures')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='information_attachment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_attachment.product')),
            ],
            options={
                'verbose_name': 'Order product',
                'verbose_name_plural': 'Order products',
            },
        ),
    ]
