# Generated by Django 3.2.8 on 2021-10-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_attachment', '0002_auto_20211026_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='picture',
            field=models.ImageField(null=True, upload_to='product_pictures'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='picture',
            field=models.ImageField(null=True, upload_to='product_pictures'),
        ),
        migrations.CreateModel(
            name='ImageOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_attachment.product')),
            ],
        ),
    ]
