# Generated by Django 3.2.8 on 2021-10-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information_attachment', '0003_auto_20211026_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='order_pictures')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_attachment.order')),
            ],
        ),
    ]
