# Generated by Django 3.2.8 on 2021-10-26 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('information_attachment', '0004_imageorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='imageorderproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='picture',
        ),
        migrations.AlterField(
            model_name='imageorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique book copy ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageorderproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique book copy ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageorderproduct',
            name='image',
            field=models.ImageField(upload_to='product_pictures'),
        ),
    ]
