# Generated by Django 3.2.8 on 2021-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_attachment', '0006_auto_20211026_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.FileField(blank=True, null=True, upload_to='order files'),
        ),
        migrations.AlterField(
            model_name='imageorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_pictures'),
        ),
        migrations.AlterField(
            model_name='imageorderproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_pictures'),
        ),
    ]
